import vtk
rw = vtk.vtkRenderWindow()
rw.SetOffScreenRendering(1)
r = vtk.vtkRenderer()
rw.AddRenderer(r)
vtk.vtkOSPRayRendererNode.SetRendererType('pathtracer', r)
vtk.vtkOSPRayRendererNode.SetSamplesPerPixel(1, r)
vtk.vtkOSPRayRendererNode.SetMaxFrames(100, r)
image = vtk.vtkImageData()
image.SetDimensions(10,10,10)
image.AllocateScalars(vtk.VTK_UNSIGNED_CHAR, 1)
mapper = vtk.vtkSmartVolumeMapper()
mapper.SetInputData(image)
mapper.SetRequestedRenderModeToOSPRay()
vol = vtk.vtkVolume()
vol.SetMapper(mapper)
r.AddVolume(vol)
rw.Render()
print('OK')
