from __future__ import annotations

from typing import Dict, Tuple

TOTALSEG_TOTAL: Dict[int, Tuple[str, str]] = {
    # Organs (category "tissue")
    1:  ("脾脏", "tissue"),
    2:  ("右肾", "tissue"),
    3:  ("左肾", "tissue"),
    4:  ("胆囊", "tissue"),
    5:  ("肝脏", "tissue"),
    6:  ("胃", "tissue"),
    7:  ("胰腺", "tissue"),
    8:  ("右肾上腺", "tissue"),
    9:  ("左肾上腺", "tissue"),
    # Lungs (category "tissue")
    10: ("左上肺叶", "tissue"),
    11: ("左下肺叶", "tissue"),
    12: ("右上肺叶", "tissue"),
    13: ("右中肺叶", "tissue"),
    14: ("右下肺叶", "tissue"),
    # Digestive/Respiratory/Endocrine (category "tissue")
    15: ("食道", "tissue"),
    16: ("气管", "tissue"),
    17: ("甲状腺", "tissue"),
    18: ("小肠", "tissue"),
    19: ("十二指肠", "tissue"),
    20: ("结肠", "tissue"),
    21: ("膀胱", "tissue"),
    22: ("前列腺", "tissue"),
    23: ("左肾囊肿", "tissue"),
    24: ("右肾囊肿", "tissue"),
    # Spine (category "bone")
    25: ("骶骨", "bone"),
    26: ("S1椎体", "bone"),
    27: ("L5椎体", "bone"),
    28: ("L4椎体", "bone"),
    29: ("L3椎体", "bone"),
    30: ("L2椎体", "bone"),
    31: ("L1椎体", "bone"),
    32: ("T12胸椎", "bone"),
    33: ("T11胸椎", "bone"),
    34: ("T10胸椎", "bone"),
    35: ("T9胸椎", "bone"),
    36: ("T8胸椎", "bone"),
    37: ("T7胸椎", "bone"),
    38: ("T6胸椎", "bone"),
    39: ("T5胸椎", "bone"),
    40: ("T4胸椎", "bone"),
    41: ("T3胸椎", "bone"),
    42: ("T2胸椎", "bone"),
    43: ("T1胸椎", "bone"),
    44: ("C7颈椎", "bone"),
    45: ("C6颈椎", "bone"),
    46: ("C5颈椎", "bone"),
    47: ("C4颈椎", "bone"),
    48: ("C3颈椎", "bone"),
    49: ("C2颈椎", "bone"),
    50: ("C1颈椎", "bone"),
    # Heart (category "tissue")
    51: ("心脏", "tissue"),
    # Major Vessels (category "vessel")
    52: ("主动脉", "vessel"),
    53: ("肺静脉", "vessel"),
    54: ("头臂干", "vessel"),
    55: ("右锁骨下动脉", "vessel"),
    56: ("左锁骨下动脉", "vessel"),
    57: ("右颈总动脉", "vessel"),
    58: ("左颈总动脉", "vessel"),
    59: ("左头臂静脉", "vessel"),
    60: ("右头臂静脉", "vessel"),
    61: ("左心耳", "vessel"),
    62: ("上腔静脉", "vessel"),
    63: ("下腔静脉", "vessel"),
    64: ("门静脉及脾静脉", "vessel"),
    65: ("左髂动脉", "vessel"),
    66: ("右髂动脉", "vessel"),
    67: ("左髂静脉", "vessel"),
    68: ("右髂静脉", "vessel"),
    # Limbs & Girdle Bones (category "bone")
    69: ("左肱骨", "bone"),
    70: ("右肱骨", "bone"),
    71: ("左肩胛骨", "bone"),
    72: ("右肩胛骨", "bone"),
    73: ("左锁骨", "bone"),
    74: ("右锁骨", "bone"),
    75: ("左股骨", "bone"),
    76: ("右股骨", "bone"),
    77: ("左髋骨", "bone"),
    78: ("右髋骨", "bone"),
    # CNS (category "tissue")
    79: ("脊髓", "tissue"),
    # Gluteal Muscles (category "tissue")
    80: ("左臀大肌", "tissue"),
    81: ("右臀大肌", "tissue"),
    82: ("左臀中肌", "tissue"),
    83: ("右臀中肌", "tissue"),
    84: ("左臀小肌", "tissue"),
    85: ("右臀小肌", "tissue"),
    # Back & Hip Muscles (category "tissue")
    86: ("左竖脊肌群", "tissue"),
    87: ("右竖脊肌群", "tissue"),
    88: ("左髂腰肌", "tissue"),
    89: ("右髂腰肌", "tissue"),
    # Head (category "tissue")
    90: ("大脑", "tissue"),
    # Skull (category "bone")
    91: ("颅骨", "bone"),
    # Ribs Left 1-12 (category "bone")
    92:  ("左第1肋骨", "bone"),
    93:  ("左第2肋骨", "bone"),
    94:  ("左第3肋骨", "bone"),
    95:  ("左第4肋骨", "bone"),
    96:  ("左第5肋骨", "bone"),
    97:  ("左第6肋骨", "bone"),
    98:  ("左第7肋骨", "bone"),
    99:  ("左第8肋骨", "bone"),
    100: ("左第9肋骨", "bone"),
    101: ("左第10肋骨", "bone"),
    102: ("左第11肋骨", "bone"),
    103: ("左第12肋骨", "bone"),
    # Ribs Right 1-12 (category "bone")
    104: ("右第1肋骨", "bone"),
    105: ("右第2肋骨", "bone"),
    106: ("右第3肋骨", "bone"),
    107: ("右第4肋骨", "bone"),
    108: ("右第5肋骨", "bone"),
    109: ("右第6肋骨", "bone"),
    110: ("右第7肋骨", "bone"),
    111: ("右第8肋骨", "bone"),
    112: ("右第9肋骨", "bone"),
    113: ("右第10肋骨", "bone"),
    114: ("右第11肋骨", "bone"),
    115: ("右第12肋骨", "bone"),
    # Sternum & Costal Cartilages (category "bone")
    116: ("胸骨", "bone"),
    117: ("肋软骨", "bone"),
}


# TotalSegmentator total_mr (Dataset850/851/852, MRI) 的 label 映射。
# 注意：MR 模型的标签编号与 CT total(117类) 完全不同，仅 50 类，顺序见
# Dataset852_TotalSegMRI_total_3mm_1088subj/.../dataset.json。
TOTALSEG_TOTAL_MR: Dict[int, Tuple[str, str]] = {
    1:  ("脾脏", "tissue"),
    2:  ("右肾", "tissue"),
    3:  ("左肾", "tissue"),
    4:  ("胆囊", "tissue"),
    5:  ("肝脏", "tissue"),
    6:  ("胃", "tissue"),
    7:  ("胰腺", "tissue"),
    8:  ("右肾上腺", "tissue"),
    9:  ("左肾上腺", "tissue"),
    10: ("左肺", "tissue"),
    11: ("右肺", "tissue"),
    12: ("食道", "tissue"),
    13: ("小肠", "tissue"),
    14: ("十二指肠", "tissue"),
    15: ("结肠", "tissue"),
    16: ("膀胱", "tissue"),
    17: ("前列腺", "tissue"),
    18: ("骶骨", "bone"),
    19: ("椎体骨(整体)", "bone"),
    20: ("椎间盘", "tissue"),
    21: ("脊髓", "tissue"),
    22: ("心脏", "tissue"),
    23: ("主动脉", "vessel"),
    24: ("下腔静脉", "vessel"),
    25: ("门静脉及脾静脉", "vessel"),
    26: ("左髂动脉", "vessel"),
    27: ("右髂动脉", "vessel"),
    28: ("左髂静脉", "vessel"),
    29: ("右髂静脉", "vessel"),
    30: ("左肱骨", "bone"),
    31: ("右肱骨", "bone"),
    32: ("左肩胛骨", "bone"),
    33: ("右肩胛骨", "bone"),
    34: ("左锁骨", "bone"),
    35: ("右锁骨", "bone"),
    36: ("左股骨", "bone"),
    37: ("右股骨", "bone"),
    38: ("左髋骨", "bone"),
    39: ("右髋骨", "bone"),
    40: ("左臀大肌", "tissue"),
    41: ("右臀大肌", "tissue"),
    42: ("左臀中肌", "tissue"),
    43: ("右臀中肌", "tissue"),
    44: ("左臀小肌", "tissue"),
    45: ("右臀小肌", "tissue"),
    46: ("左竖脊肌群", "tissue"),
    47: ("右竖脊肌群", "tissue"),
    48: ("左髂腰肌", "tissue"),
    49: ("右髂腰肌", "tissue"),
    50: ("大脑", "tissue"),
}


# SynthSeg (DIPY 版) 脑部分割的 label 映射。
# label 值遵循 FreeSurfer 分类（与 DIPY dipy.nn.torch.synthseg 的 label_dict 一致）。
# 脑部结构无骨骼/血管，故 category 全部归为 "tissue"（软组织/神经组织/脑脊液）。
SYNTHSEG_LABELS: Dict[int, Tuple[str, str]] = {
    2:  ("左脑白质", "tissue"),
    3:  ("左脑皮层", "tissue"),
    4:  ("左侧脑室", "tissue"),
    5:  ("左下侧脑室", "tissue"),
    7:  ("左小脑白质", "tissue"),
    8:  ("左小脑皮层", "tissue"),
    10: ("左丘脑", "tissue"),
    11: ("左尾状核", "tissue"),
    12: ("左壳核", "tissue"),
    13: ("左苍白球", "tissue"),
    14: ("第三脑室", "tissue"),
    15: ("第四脑室", "tissue"),
    16: ("脑干", "tissue"),
    17: ("左海马", "tissue"),
    18: ("左杏仁核", "tissue"),
    24: ("脑脊液", "tissue"),
    26: ("左伏隔核", "tissue"),
    28: ("左腹侧DC", "tissue"),
    41: ("右脑白质", "tissue"),
    42: ("右脑皮层", "tissue"),
    43: ("右侧脑室", "tissue"),
    44: ("右下侧脑室", "tissue"),
    46: ("右小脑白质", "tissue"),
    47: ("右小脑皮层", "tissue"),
    49: ("右丘脑", "tissue"),
    50: ("右尾状核", "tissue"),
    51: ("右壳核", "tissue"),
    52: ("右苍白球", "tissue"),
    53: ("右海马", "tissue"),
    54: ("右杏仁核", "tissue"),
    58: ("右伏隔核", "tissue"),
    60: ("右腹侧DC", "tissue"),
}

# TotalSegmentator brain_structures (Dataset409, 官方脑区 16 类, 需学术/商业授权)
# 含左右? 否: 官方输出为跨左右整体叶 + 深部核团, 颞叶=15 (含白质全叶)
TS_BRAIN_STRUCTURES: Dict[int, Tuple[str, str]] = {
    1:  ("脑干", "tissue"),
    2:  ("蛛网膜下腔", "tissue"),
    3:  ("静脉窦", "tissue"),
    4:  ("透明隔", "tissue"),
    5:  ("小脑", "tissue"),
    6:  ("尾状核", "tissue"),
    7:  ("豆状核", "tissue"),
    8:  ("岛叶皮质", "tissue"),
    9:  ("内囊", "tissue"),
    10: ("脑室", "tissue"),
    11: ("中央沟", "tissue"),
    12: ("额叶", "tissue"),
    13: ("顶叶", "tissue"),
    14: ("枕叶", "tissue"),
    15: ("颞叶 (官方)", "tissue"),
    16: ("丘脑", "tissue"),
}
